stuff

diff --git a/gitdbdump b/gitdbdump
--- a/gitdbdump
+++ b/gitdbdump
@@ -1,90 +1,90 @@
-#!/usr/bin/env bash
+#!/usr/bin/env ruby
 
-# DBMS
-function list_mysql {
-	echo "show databases;" | mysql --column-names=false | grep -v information_schema
-}
+require "fileutils"
 
-function dump_mysql {
-	db_name=$1
-	dump_file=$2
-	mysqldump --comments=0 --extended-insert=false $db_name > "$dump_file"
-}
+# default values
+BACKUP_DIR = "/Users/fabian/var/backups/dbdumps.git"
+PERMISSIONS = [:owner]
+USAGE = "Usage: 
 
-function list_postgres {
-	echo "SELECT datname FROM pg_database;" | psql -t postgres -A | grep -v "^template.$"
-}
+  gitdbdump backup                     perform a backup of all databases of all installed RDBMS
+  gitdbdump clean                      clean out old backups
+  gitdbdump checkpoint <name>          save a manual checkpoint (which won't be deleted by clean)
+  
+"
 
-function dump_postgres {
-	db_name=$1
-	dump_file=$2
-	pg_dump $db_name > $dump_file
-}
-# End DBMS
+# Functions: Logging
+def error(msg)
+  puts "error: #{msg}"
+end
 
-# ensure good permissions:
-umask 0077
+def printUsageAndExit
+  puts USAGE
+  exit(-1)
+end
 
-if [[ $(id -u) -ne "0" ]]; then
-	echo "Must be root to create backups."
-	exit 1
-fi
+# Functions: rdbms
+def installed_rdbms
+  installed = []
+  `which mysqldump`
+  installed << "mysql" if $?.success?
+  `which pg_dump`
+  installed << "postgresql" if $?.success?
 
-# DefaultConfiguration
-databases="mysql"
-backup_basedir="/var/backups/dbdumps.git/"
-backup_user="root"
-backup_permissions="600"
+  installed  
+end
 
-# load Configuration
-if [[ -e "/etc/gitdbdump.conf" ]]; then
-    source /etc/gitdbdump.conf
+def list_mysql
+  `echo "show databases;" | mysql --column-names=false`
+end
+
+def dump_mysql(db,file)
+	`mysqldump --comments=0 --extended-insert=false #{db} > "#{file}"`
+end
+
+def list_postgres
+	list = `echo "SELECT datname FROM pg_database;" | psql -t postgres -A`
+	if $?.success?
+	  return list.split("\n")
+  else
+	  error("could not connect to postgres")
+    return []
+  end
+end
+
+def dump_postgres(db,file)
+	`pg_dump #{db} > "#{file}"`
+end
+
+# Functions: git
+def git_cmd(command)
+  `GIT_DIR="#{File.join(BACKUP_DIR,".git")}" GIT_WORK_TREE="#{BACKUP_DIR}" git #{command}`  
+end
+
+
+
+# MAIN
+
+printUsageAndExit unless ARGV.length >= 1
+case ARGV[0]
+when "backup"
+  puts "doing backup"
+  
+  FileUtils.mkdir_p BACKUP_DIR
+  git_cmd "init"
+  installed_rdbms.each do |rdbms|
+    FileUtils.mkdir_p File.join(BACKUP_DIR, rdbms)
+    send("list_#{rdbms}").each do |db|
+      puts db
+    end
+  end
+  
+when "clean"
+  puts "doing clean"
+when "checkpoint"
+  printUsageAndExit unless ARGV.length == 2
+  
+  puts "creating a checkpint"
 else
-    echo "Warning: /etc/dbbackup.conf not found" 
-fi
-
-# create and enter BaseDir
-if [[ ! -d "$backup_basedir" ]]; then
-	echo "$0: Warning: $backup_basedir doesn't exist."
-	mkdir -p $backup_basedir
-fi
-cd $backup_basedir
-
-# git init
-git init
-
-# better git gc performance
-git config pack.threads 1
-git config pack.windowMemory 100m
-git config pack.window 15
-git config core.compression 9
-
-
-# empty repo
-rm -Rf $backup_basedir/*
-
-# dump
-for db in $databases; do
-	echo "= dumping $db databases"
-	dump_dir="$backup_basedir/$db/"
-	if [[ ! -d "$dump_dir" ]]; then
-		mkdir -p $dump_dir
-	fi
-	for db_name in `list_$db`; do
-		echo "-- dumping $db_name"
-		dump_file="$dump_dir/$db_name.sql"
-		dump_$db $db_name $dump_file
-		
-	done
-done
-
-# commit to repository
-echo "= adding to repository"
-git add *
-COMMIT_MSG="`date`"
-git commit -a -m "$COMMIT_MSG"
-git gc
-
-# Fix perms
-chown -R $backup_user $backup_basedir
-chmod -R $backup_permissions $backup_basedir
+  printUsageAndExit
+end
